// xspace-agents/agent-voice-chat/packages/vue/src/AudioVisualizer.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = withDefaults(defineProps<{
  level: number;
  bars?: number;
  barWidth?: number;
  barGap?: number;
  height?: number;
  color?: string;
  inactiveColor?: string;
}>(), {
  bars: 20,
  barWidth: 3,
  barGap: 2,
  height: 40,
  color: '#3b82f6',
  inactiveColor: '#e5e7eb',
});

const activeBars = computed(() => Math.round(props.level * props.bars));
const totalWidth = computed(() => props.bars * props.barWidth + (props.bars - 1) * props.barGap);

const barElements = computed(() =>
  Array.from({ length: props.bars }, (_, i) => {
    const isActive = i < activeBars.value;
    const centerDistance = Math.abs(i - props.bars / 2) / (props.bars / 2);
    const barHeight = isActive
      ? props.height * (0.3 + 0.7 * (1 - centerDistance) * Math.min(props.level * 3, 1))
      : props.height * 0.15;

    return { isActive, barHeight };
  }),
);
</script>

<template>
  <div
    class="avc-audio-visualizer"
    :style="{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: `${barGap}px`,
      width: `${totalWidth}px`,
      height: `${height}px`,
    }"
  >
    <div
      v-for="(bar, i) in barElements"
      :key="i"
      :style="{
        width: `${barWidth}px`,
        height: `${bar.barHeight}px`,
        backgroundColor: bar.isActive ? color : inactiveColor,
        borderRadius: `${barWidth / 2}px`,
        transition: 'height 0.05s ease, background-color 0.1s ease',
      }"
    />
  </div>
</template>

// xspace-agents/agent-voice-chat/packages/react/src/AudioVisualizer.tsx
import React, { useMemo } from 'react';
import type { AudioVisualizerProps } from './types';

/**
 * Renders a bar-style audio level visualizer.
 *
 * @example
 * ```tsx
 * <AudioVisualizer level={audioLevel} bars={20} height={40} color="#3b82f6" />
 * ```
 */
export const AudioVisualizer: React.FC<AudioVisualizerProps> = ({
  level,
  bars = 20,
  barWidth = 3,
  barGap = 2,
  height = 40,
  color = '#3b82f6',
  inactiveColor = '#e5e7eb',
  className,
  style,
}) => {
  const activeBars = Math.round(level * bars);
  const totalWidth = bars * barWidth + (bars - 1) * barGap;

  const barElements = useMemo(() => {
    return Array.from({ length: bars }, (_, i) => {
      const isActive = i < activeBars;
      // Create a natural waveform shape: taller in center, shorter at edges
      const centerDistance = Math.abs(i - bars / 2) / (bars / 2);
      const barHeight = isActive
        ? height * (0.3 + 0.7 * (1 - centerDistance) * Math.min(level * 3, 1))
        : height * 0.15;

      return (
        <div
          key={i}
          style={{
            width: barWidth,
            height: barHeight,
            backgroundColor: isActive ? color : inactiveColor,
            borderRadius: barWidth / 2,
            transition: 'height 0.05s ease, background-color 0.1s ease',
          }}
        />
      );
    });
  }, [activeBars, bars, barWidth, height, color, inactiveColor, level]);

  return (
    <div
      className={className}
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: barGap,
        width: totalWidth,
        height,
        ...style,
      }}
    >
      {barElements}
    </div>
  );
};

AudioVisualizer.displayName = 'AudioVisualizer';
